export const DEFAULT_PHASE_DURATIONS = {
  daySeconds: 10,
  nightSeconds: 10,
  voteSeconds: 10,
};

export const START_COUNTDOWN_MS = 5000;
export const DAY_ZERO_DURATION_MS = 10000;
export const ELIMINATION_RESULTS_DURATION_MS = 5000;
export const NIGHT_DEATH_REVEAL_DURATION_MS = 12000;

const ROLE_TITLE_LEAD_MS = 1000;
const ROLE_REVEAL_HOLD_MS = 3000;
const ROLE_REVEAL_FADE_MS = 700;

export const ROLE_REVEAL_TOTAL_MS =
  ROLE_TITLE_LEAD_MS + ROLE_REVEAL_HOLD_MS + ROLE_REVEAL_FADE_MS;
